	USE FLIPYEARDB;


-- PERFIL GERAL CLIENTS
	INSERT INTO CLIENTES_TB (ID_ENDERECO, NM_CLIENTE, DS_TELEFONE, DS_CPF, DS_EMAIL,  DS_SENHA)
							VALUES (1, "rOGERIO SKYLAB", "55(11) 396546432", 546546654, "rogerio@gmail.com", "12345678");
	select *
			from clientes_tb			 AS C_TB
				INNER JOIN ENDERECOS_TB AS E_TB ON E_TB.ID_ENDERECO= C_TB.ID_ENDERECO;

-- ENDERECO
	INSERT INTO ENDERECOS_TB (DS_CEP, NM_CIDADE, DS_COMPLEMENTO, NR_NUMERO)
							 VALUES("666666", "JUÁ", "", 69); 
							 
-- PRODUTOS
	INSERT INTO PRODUTO_TB  (ID_CATEGORIA, NM_PRODUTO, VL_PRECO, VL_PRECO_PROMOCIONA, BT_PRMOCAO, BT_DESTAQUE, BT_DISPONIVEL, QTD_ESTOQUE, DS_DETALHES)
							VALUES(1, "Madeira", 15.00, 0.00, false, true, false, 150, "madeira de boa qualidade madeira boa hein madeira");
                            
	INSERT INTO CATEGORIA_TB (NM_CATEGORIA)
							 VALUES("Fliperama");
	SELECT *
		FROM PRODUTO_TB 		AS P 
	INNER JOIN CATEGORIA_TB		AS C ON C.ID_CATEGORIA = P.ID_CATEGORIA;