CREATE DATABASE FLIPYEARDB;

USE FLIPYEARDB;

CREATE TABLE USERS_TB(
	ID_USUARIO			INT primary KEY auto_increment,
    ID_ENDERECO			INT NOT NULL,
    NM_USUARIO			VARCHAR(100) NOT NULL,
    DS_TELEFONE			VARCHAR(100) NOT NULL,
    DS_CPF				VARCHAR(11)  NOT NULL,
    DS_EMAIL			VARCHAR(100) NOT NULL,
    DS_SENHA			VARCHAR(50)  NOT NULL,
	DS_TIER				VARCHAR(50),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO_TB(ID_ENDERECO)
);

drop table USERS_TB;

CREATE TABLE ENDERECO_TB(
	ID_ENDERECO			INT primary KEY auto_increment,
    DS_CEP				INT NOT NULL,
    NM_CIDADE			VARCHAR(100) NOT NULL,
    NM_RUA				VARCHAR(100) NOT NULL,
    DS_COMPLEMENTO		VARCHAR(100),
    NR_NUMERO			INT NOT NULL
);
						
-- ------------------------ --
-- ------------------------ --

CREATE TABLE PRODUTO_TB(
	ID_PRODUTO					INT primary KEY auto_increment,
	ID_CATEGORIA				INT NOT NULL,
	NM_PRODUTO					VARCHAR(100) NOT NULL,
    VL_PRECO					DECIMAL(21, 4) NOT NULL,
	VL_PRECO_PROMOCIONA			DECIMAL(21, 4) NOT NULL,
    BT_DESTAQUE					BOOLEAN NOT NULL,
    BT_PRMOCAO					BOOL NOT NULL,
    BT_DISPONIVEL				BOOL NOT NULL,
    QTD_ESTOQUE					INT NOT NULL,
    DS_DETALHES					varchar(500) NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_TB(ID_CATEGORIA)    
);


CREATE TABLE CATEGORIA_TB (
	ID_CATEGORIA				INT primary KEY auto_increment,
    NM_CATEGORIA				VARCHAR(100)
);

CREATE TABLE IMAGEM_PRODUTO_TB(
	ID_IMAGEM_PRODUTO			INT primary KEY auto_increment,
    ID_PRODUTO					INT,
    IMG_PRODUTO					VARCHAR(100),
    FOREIGN KEY (ID_PRODUTO) REFERENCES	PRODUTO_TB(ID_PRODUTO)
);	







